[package]
name = "riscv-emu"
version = "0.1.0"
edition = "2021"


[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
register-interface = "0.1.0"
macros = { path = "../macros" }
